name: Secrets Scan
on: [push, pull_request]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install detect-secrets
        run: pip install detect-secrets
      
      - name: Scan for secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline
          if detect-secrets audit .secrets.baseline; then
            echo "No secrets found"
          else
            echo "Potential secrets detected!" && exit 1
          fi
      
      - name: Check for blacklisted file types
        run: |
          if git ls-files | grep -E '\.pem$|\.key$|\.env$|\.pfx$|\.p12$'; then
            echo "ERROR: Forbidden file types found (.pem, .key, .env)" && exit 1
          fi
          echo "No forbidden file types found"
      
      - name: Check for unsafe Docker bindings
        run: |
          if grep -r "0\.0\.0\.0:" --include="*.yml" --include="*.yaml" --include="Dockerfile"; then
            echo "ERROR: Unsafe 0.0.0.0 binding found!" && exit 1
          fi
          echo "All bindings are localhost-only"
